#!/usr/bin/env bash

core_dir=$(dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")
vendor_cmd="$core_dir/.vendor/github.com/brettlangdon/git-vendor/bin/git-vendor"
vendor_dir=".go/.vendor"

_usage() {
	cat <<EOF
Usage:
  vendor --help
  vendor add [--prefix <dir>] <name> <repository> [<ref>]
  vendor list [<name>]
  vendor remove <name>
  vendor update <name> [<ref>]
EOF
}

case "$1" in
"" | "--help") _usage && exit ;;
esac

command="$1"
shift
case "$command" in
"add" | "list" | "remove" | "update") ;;
*) echo >&2 "error: unknown command \"$command\"" && _usage && exit 1 ;;
esac

args=("${@}")

function default_prefix() {
	if [[ "$command" == "add" ]]; then
		local prefix_called=""
		for arg in "$@"; do
			if [[ "$arg" == "--prefix" ]]; then
				prefix_called="true"
			fi
		done
		if [ -z $prefix_called ]; then
			args=("--prefix" "$vendor_dir" "${args[@]}")
		fi
	fi
}

if [ ! -d "$vendor_dir" ]; then
	mkdir "$vendor_dir"
fi

default_prefix "${args[@]}"

"$vendor_cmd" "$command" ${args[@]}
