on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

name: shellcheck-core
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
